# Site settings
title: LJW's Blog            # 博客标题
SEOTitle: LJW's Blog               # 显示在浏览器上搜索的时候显示的标题
header-img: img/post-bg-index.jpg    # 显示在首页的背景图片
email: 754474446@qq.com            # 个人邮箱
description: "Every failure is leading towards success."  # 网站介绍
keyword: "LJW, Java"  #关键词
url: "https://jarrett-98.github.io/"          # your host, for absolute URL；这个就是填写你的博客地址
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/jarrett-98/jarrett-98.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "但行好事，莫问前程。"
sidebar-avatar: /img/will-wang.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     
zhihu_username:     
github_username:    jarrett-98
# facebook_username:  username
# jianshu_username:   jianshu_id
twitter_username:   
jianshu_id: 


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: flyingwzb

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 44b5a485f395e1a3b69e                            #生成的clientID
  clientSecret: 40d03830790b9409b569ec05c58cb93b409c0efc    #生成的clientSecret
  repo: jarrett-98.github.io   #仓库名称
  owner: jarrett-98    #github用户名
  admin: jarrett-98
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 4e808c706305a97f600407f99a381451

# Google Analytics
#ga_track_id: 'UA-137811562-1'            # Format: UA-xxxxxx-xx
#ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto


# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页


# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true


# Friends
friends: [
{title: "暂无",},
# {title: "书舟网",href: "http://kindle.archiew.top/"},
# {title: "阮一峰",href: "http://www.ruanyifeng.com/home.html"},
# {title: "阿里巴巴",href: "https://www.alibabagroup.com/cn/global/home"},
# {title: "腾讯",href: "https://www.tencent.com/zh-cn/index.html"},
# {title: "字节跳动",href: "https://www.bytedance.com/zh"}
]


# 支付宝、微信打赏二维码
alipay_qr_img: 

wechat_qr_img: 